### ISSUE TITLE
Merge this repo into sublimehq/Packages

### ISSUE THREAD

**Issue by jrappen** [joshnh/HTML-Snippets#19]
Merge this repo into [sublimehq/Packages](http://github.com/sublimehq/Packages).

**Comment by joshnh** [comment]
@jrappen "Pull requests for new packages won't be accepted at this stage, as it can cause issues for users who have a package with the same name via Package Control. There are some planned changes in the future that will address this." Has that been addressed yet?

**Comment by jrappen** [comment]
@joshnh Not that I know of.
